/** @type {import('tailwindcss').Config} */
// Vibrant Scholastic — ported verbatim from the Stitch export
// (stitch_little_lillies_digital_presence (1).zip, vibrant_scholastic).
// Token names and values match their tailwind.config exactly so the markup in
// their code.html can be used as-is.
module.exports = {
    content: ['./*.html', './main.js'],
    plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')],
    darkMode: 'class',
    theme: {
        extend: {
            colors: {
                'surface-container': '#f0ede9',
                'on-primary-fixed-variant': '#594400',
                'on-primary-container': '#705700',
                'tertiary-container': '#a4e558',
                'surface-dim': '#dcdad5',
                'on-secondary-fixed-variant': '#1f477b',
                'tertiary-fixed-dim': '#99d94d',
                'on-surface-variant': '#4e4633',
                'primary-fixed': '#ffdf92',
                'primary-fixed-dim': '#f2c025',
                primary: '#755b00',
                'outline-variant': '#d2c5ad',
                'secondary-fixed': '#d5e3ff',
                background: '#fcf9f4',
                'on-tertiary-fixed': '#0f2000',
                'surface-container-high': '#ebe8e3',
                'surface-bright': '#fcf9f4',
                'on-tertiary-fixed-variant': '#2e4f00',
                surface: '#fcf9f4',
                'on-tertiary-container': '#3c6500',
                'tertiary-fixed': '#b4f666',
                'on-surface': '#1c1c19',
                'surface-container-low': '#f6f3ee',
                'surface-tint': '#755b00',
                'secondary-fixed-dim': '#a7c8ff',
                secondary: '#3a5f94',
                'surface-container-highest': '#e5e2dd',
                'on-secondary-container': '#294f83',
                'on-primary-fixed': '#241a00',
                'on-primary': '#ffffff',
                'inverse-surface': '#31302d',
                tertiary: '#3f6900',
                'on-error': '#ffffff',
                'on-secondary': '#ffffff',
                error: '#ba1a1a',
                'on-secondary-fixed': '#001b3c',
                'secondary-container': '#9fc2fe',
                'surface-variant': '#e5e2dd',
                'inverse-primary': '#f2c025',
                'primary-container': '#ffcc33',
                'on-error-container': '#93000a',
                'on-tertiary': '#ffffff',
                'inverse-on-surface': '#f3f0eb',
                outline: '#807661',
                'on-background': '#1c1c19',
                'surface-container-lowest': '#ffffff',
                'error-container': '#ffdad6',

                // ---- Brand manual palette (June 2026) ----------------------
                'brand-purple': '#421163',
                'brand-purple-soft': '#865FB3',
                'brand-purple-wash': '#F1EAF8',
                'brand-blue': '#3060A7',
                'brand-blue-wash': '#E8EFF8',
                'brand-green': '#6FAB22',
                'brand-green-wash': '#EFF7E3',
                'brand-pink-wash': '#FBEDF3',
                'brand-amber-wash': '#FFF6DC',
                // Kept only so the brand lockup and the publishing gate still resolve.
                plum: '#421163',
                'gate-amber': '#c9873a',
            },
            borderRadius: {
                DEFAULT: '1rem',
                lg: '2rem',
                xl: '3rem',
                full: '9999px',
            },
            spacing: {
                'container-max': '1280px',
                base: '8px',
                'section-padding-mobile': '64px',
                gutter: '24px',
                'section-padding-desktop': '120px',
            },
            maxWidth: {
                'container-max': '1280px',
            },
            fontFamily: {
                'headline-lg': ['Quicksand', 'sans-serif'],
                'headline-lg-mobile': ['Quicksand', 'sans-serif'],
                'headline-md': ['Quicksand', 'sans-serif'],
                'label-bold': ['Be Vietnam Pro', 'sans-serif'],
                'display-lg': ['Quicksand', 'sans-serif'],
                'body-lg': ['Be Vietnam Pro', 'sans-serif'],
                'body-md': ['Be Vietnam Pro', 'sans-serif'],
            },
            fontSize: {
                'headline-lg': ['48px', { lineHeight: '1.2', fontWeight: '700' }],
                'headline-lg-mobile': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
                'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '600' }],
                'label-bold': ['14px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '700' }],
                'display-lg': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
                'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
                'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
            },
            keyframes: {
                'spin-slow': { from: { transform: 'rotate(0deg)' }, to: { transform: 'rotate(360deg)' } },
            },
            animation: {
                'spin-slow': 'spin-slow 40s linear infinite',
            },
        },
    },
};
